setup:
    interpolation_grid_min: 0
    interpolation_grid_max: 31000
    interpolation_grid_inc: 10
    max_gap_fill: 0
global_attrs:
    title: RAPSODI Radiosonde Measurements during ${main.campaign}, ${main.platform} (Level 2)
    summary: "Vertical atmospheric profile, retrieved from atmospheric sounding attached to a helium filled ballon."
    creator_name: Marius Winkler, Marius Rixen
    creator_email: marius.winkler@mpimet.mpg.de, marius.rixen@mpimet.mpg.de
    project: ORCESTRA, PERCUSION, BOW-TIE, PICCOLO, SCORE, MAESTRO
    featureType: profile
    platform: ${main.platform}
    source: Radiosondes
    history: "Vaisala Sounding System MW41 (2.21.0.7); Quality control with {package} ({version}); Level 1 processing with {package} ({version}); Level 2 processing with {package} ({version}) on {date}."
    license: CC-BY-4.0
    references: https://github.com/observingClouds/pysonde
    keywords: ORCESTRA, Radiosonde Profil, Sounding, ${main.platform}

#    title: ${main.campaign} level 2 sounding data
#    source: "{input_file}"
#    version: "{version}"
#    history: "created with {package} ({version}) on {date}"
#    description: ???
#    campaign_id: ${main.campaign_id}
#    platform: ${main.platform}
#    instrument: "Radiosonde RS41-SGP by Vaisala"
#    doi: ???
#    featureType: "trajectory"
#    acknowledgement: ???
#    references: ???
#    Conventions: "CF-1.7"

coordinates:
    sounding:
        dimension: ${runtime.sounding_dim}
        attrs:
            units: ""
        internal_varname: "sounding"
    height:
        dimension: ${runtime.level_dim}
        attrs:
            standard_name: "geopotential_height"
            long_name: "geopotential height from PTU"
            units: "m"
            axis: "Z"
            positive: "up"
        encodings:
            dtype: "float32"
        internal_varname: "height"
variables:
    alt:
        attrs:
            standard_name: "altitude"
            long_name: "altitude height above reference ellipsoid (WGS84)"
            units: "m"
            axis: "Z"
            positive: "up"
        encodings:
            dtype: "float32"
            _FillValue: False
        coordinates:
            - sounding
            - height
        internal_varname: "altitude_WGS84"
    launch_time:
        attrs:
            standard_name: "time"
            long_name: "time at which the sounding started"
        encodings:
            dtype: "float64"
            units: "seconds since 2020-01-01"
            calendar: "proleptic_gregorian"
        coordinates:
            - sounding
        internal_varname : "launch_time"
    platform:
        attrs:
            long_name: "platform identifier"
            coordinates: "launch_time"
            flag_meanings: "BCO Meteor"
            flag_values: "[1, 2]"
            units: "1"
        encodings:
            dtype: "int8"
        coordinates:
            - sounding
        internal_varname: "platform"
    ascent_flag:
        attrs:
            long_name: "indicator of vertical flight direction"
            flag_meanings: "ascending descending"
            flag_values: "[0,1]"
            valid_range: "[ 0,1 ]"
            coordinates: "launch_time"
        encodings:
            dtype: "int8"
        coordinates:
            - sounding
        internal_varname: "ascent_flag"
    sounding:
        attrs:
            cf_role: "trajecotry_id"
            long_name: "sounding identifier"
            description: "unique string describing the soundings origin (PLATFORM_SND-DIRECTION_LAT_LON_TIME)"
        encodings:
            dtype: "str"
        format: ${main.platform}__{direction}__{lat:3.2f}_{lon:4.2f}__%Y%m%d%H%M
        coordinates:
            - sounding
        internal_varname: "sounding"
    flight_time:
        attrs:
            standard_name: "time"
            long_name: "time at pressure level"
            coordinates: "lon lat height launch_time sounding"
            ancillary_variables: "N_ptu m_ptu"
            cell_methods: "height: mean (interval: 10 m comment: m_ptu)"
        encodings:
            units: "seconds since 2020-01-01"
            calendar: "proleptic_gregorian"
            dtype: "float64"
        coordinates:
            - sounding
            - height
        internal_varname : "flight_time"
    p:
        attrs:
            standard_name: "air_pressure"
            long_name: "pressure"
            units: "Pa"
            coordinates: "lon lat height flight_time launch_time sounding"
            ancillary_variables: "N_ptu m_ptu"
            cell_methods: "height: mean (interval: 10 m comment: m_ptu)"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "pressure"
    lat:
        attrs:
            standard_name: "latitude"
            long_name: "latitude"
            axis: "Y"
            units: "degree_north"
            ancillary_variables: "N_gps m_gps"
            cell_methods: "height: mean (interval: 10 m comment: m_gps)"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "latitude"
    lon:
        attrs:
            standard_name: "longitude"
            long_name: "longitude"
            axis: "X"
            units: "degree_east"
            ancillary_variables: "N_gps m_gps"
            cell_methods: "height: mean (interval: 10 m comment: m_gps)"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "longitude"
    dz:
        attrs:
            long_name: "ascent/descent rate of measuring device"
            description: "calculated from interpolated geopotential height changes (artifical rate)"
            units: "m/s"
            coordinates: "lon lat height flight_time launch_time sounding"
            ancillary_variables: "N_ptu m_ptu"
            cell_methods: "height: mean (interval: 10 m comment: m_ptu)"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname : "ascent_rate"
    ta:
        attrs:
            standard_name: "air_temperature"
            long_name: "air temperature"
            units: "K"
            coordinates: "lon lat height flight_time launch_time sounding"
            cell_methods: "height: point (derived from averaged theta)"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname : "temperature"
    dp:
        attrs:
            standard_name: "dew_point_temperature"
            long_name: "dew point temperature"
            units: "K"
            coordinates: "lon lat flight_time launch_time"
            ancillary_variables: "N_ptu m_ptu"
            cell_methods: "height: mean (interval: 10 m comment: m_ptu)"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "dewpoint"
    wspd:
        attrs:
            standard_name: "wind_speed"
            long_name: "wind speed"
            units: "m/s"
            cell_methods: "height: point (derived from averaged u, v)"
            coordinates: "launch_time flight_time lon lat"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "wind_speed"
    u:
        attrs:
            standard_name: "eastward_wind"
            long_name: "u-component of the wind"
            units: "m/s"
            ancillary_variables: "N_gps m_gps"
            cell_methods: "height: mean (interval: 10 m comment: m_gps)"
            coordinates: "launch_time flight_time lon lat"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "wind_u"
    v:
        attrs:
            standard_name: "northward_wind"
            long_name: "v-component of the wind"
            units: "m/s"
            ancillary_variables: "N_gps m_gps"
            cell_methods: "height: mean (interval: 10 m comment: m_gps)"
            coordinates: "launch_time flight_time lon lat"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "wind_v"
    mr:
        attrs:
            standard_name: "humidity_mixing_ratio"
            long_name: "water vapor mixing ratio"
            units: "1"
            ancillary_variables: "N_ptu"
            cell_methods: "height: point (derived from averaged q)"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname : "mixing_ratio"
    theta:
        attrs:
            standard_name: "air_potential_temperature"
            long_name: "potential temperature"
            units: "K"
            coordinates: "lon lat flight_time launch_time"
            ancillary_variables: "N_ptu m_ptu"
            cell_methods: "height: mean (interval: 10 m comment: m_ptu)"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "theta"
    q:
        attrs:
            standard_name: "specific_humidity"
            long_name: "specific humidity"
            units: "1"
            ancillary_variables: "N_ptu m_ptu"
            cell_methods: "height: mean (interval: 10 m comment: m_ptu)"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "specific_humidity"
    wdir:
        attrs:
            standard_name: "wind_from_direction"
            long_name: "wind direction"
            units: "degree"
            coordinates: "launch_time flight_time lon lat"
            cell_methods: "height: point (derived from averaged u, v)"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "wind_direction"
    rh:
        attrs:
            standard_name: "relative_humidity"
            long_name: "relative humidity"
            units: "1"
            coordinates: "lon lat flight_time launch_time"
            cell_methods: "height: point (derived from averaged q, T, p)"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname : "relative_humidity"
    N_ptu:
        attrs:
            standard_name: "number_of_observations"
            description: "number of observations used to derive level 2 PTU-data average"
            units: "1"
            coordinates: "lon lat flight_time launch_time"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "N_ptu"
    N_gps:
        attrs:
            standard_name: "number_of_observations"
            description: "number of observations used to derive level 2 GPS-data average"
            units: "1"
            coordinates: "lon lat flight_time launch_time"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - height
        internal_varname: "N_gps"
    m_ptu:
        attrs:
            long_name: "bin method"
            description: "method used to derive level 2 PTU-data average"
            flag_meanings: "no_data interpolation averaging"
            flag_values: "[ 0, 1, 2 ]"
            coordinates: "lon lat flight_time launch_time"
        encodings:
            dtype: "int8"
        coordinates:
            - sounding
            - height
        internal_varname: "m_ptu"
    m_gps:
        attrs:
            long_name: "bin method"
            description: "method used to derive level 2 GPS-data average"
            flag_meanings: "no_data interpolation averaging"
            flag_values: "[ 0, 1, 2 ]"
            coordinates: "lon lat flight_time launch_time"
        encodings:
            dtype: "int8"
        coordinates:
            - sounding
            - height
        internal_varname: "m_gps"