global_attrs:
    title: RAPSODI Radiosonde Measurements during ${main.campaign}, ${main.platform} (Level 1)
    summary: "Vertical atmospheric profile, retrieved from atmospheric sounding attached to a helium filled ballon."
    creator_name: Marius Winkler, Marius Rixen
    creator_email: marius.winkler@mpimet.mpg.de, marius.rixen@mpimet.mpg.de
    project: ORCESTRA, PERCUSION, BOW-TIE, PICCOLO, SCORE, MAESTRO
    featureType: profile
    platform: ${main.platform}
    source: Radiosondes
    history: "Meteomodem Eoscan Software (2.1.241218); Quality control with {package} ({version}); Level 1 processing with {package} ({version}) on {date}."
    license: CC-BY-4.0
    references: https://github.com/observingClouds/pysonde
    keywords: ORCESTRA, Radiosonde Profil, Sounding, ${main.platform}
coordinates:
    sounding:
        dimension: ${runtime.sounding_dim}
        internal_varname: "sounding"
    level:
        attrs:
            long_name: "sounding height"
        dimension: ${runtime.level_dim}
variables:
    launch_time:
        attrs:
            standard_name: "time"
            long_name: "time at which the sounding started"
        encodings:
            dtype: "float64"
            units: "seconds since 2020-01-01"
            calendar: "proleptic_gregorian"
        coordinates:
            - sounding
        internal_varname : "launch_time"
    flight_time:
        attrs:
            long_name: "time at pressure level"
            axis: "T"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "seconds since 2020-01-01"
            calendar: "proleptic_gregorian"
            dtype: "float64"
        coordinates:
            - sounding
            - level
        internal_varname : "flight_time"
    dz:
        attrs:
            long_name: "ascent/descent rate of measuring device"
            description: "ascent rate is positive/ decent rate is negative"
            units: "m/s"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "m/s"
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "ascent_rate"
    p:
        attrs:
            standard_name: "air_pressure"
            long_name: "pressure"
            units: "Pa"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "Pa"
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "pressure"
    height:
        attrs:
            standard_name: "geopotential_height"
            long_name: "geopotential height retrieved from PTU"
            units: "m"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
    alt:
        attrs:
            standard_name: "altitude"
            long_name: "altitude height above reference ellipsoid (WGS84)"
            positive: "up"
            units: "m"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "height"
    ta:
        attrs:
            standard_name: "air_temperature"
            long_name: "air temperature"
            units: "K"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "temperature"
    rh:
        attrs:
            standard_name: "relative_humidity"
            long_name: "relative humidity"
            units: "1"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "humidity"
    dp:
        attrs:
            standard_name: "dew_point_temperature"
            long_name: "dew point temperature"
            units: "K"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "dew_point"
    mr:
        attrs:
            standard_name: "humidity_mixing_ratio"
            long_name: "water vapor mixing ratio"
            units: "1"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "mixing_ratio"
    wspd:
        attrs:
            standard_name: "wind_speed"
            long_name: "wind speed"
            units: "m/s"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "wind_speed"
    wdir:
        attrs:
            standard_name: "wind_from_direction"
            long_name: "wind direction"
            units: "degree"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "wind_direction"
    lat:
        attrs:
            standard_name: "latitude"
            long_name: "latitude"
            axis: "Y"
            units: "degree_north"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "latitude"
    lon:
        attrs:
            standard_name: "longitude"
            long_name: "longitude"
            axis: "X"
            units: "degree_east"
        encodings:
            dtype: "float32"
        coordinates:
            - sounding
            - level
        internal_varname : "longitude"
    sounding:
        attrs:
            cf_role: "trajecotry_id"
            long_name: "sounding identifier"
            description: "unique string describing the soundings origin (PLATFORM_SND-DIRECTION_LAT_LON_TIME)"
        encodings:
            dtype: "str"
        format: ${main.platform}__{direction}__{lat:3.2f}_{lon:4.2f}__%Y%m%d%H%M
        coordinates:
            - sounding
        internal_varname : "sounding"
    level:
        attrs:
            cf_role: "level"
            long_name: "level"
            description: "Level of measurement"
        encodings:
            dtype: "int16"
        coordinates:
            - level
        internal_varname : "level"
